# Generated by Django 4.1.2 on 2022-10-19 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_highligths"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Highligths",
            new_name="Highligth",
        ),
    ]
