# Generated by Django 3.2.6 on 2022-09-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_generalanouncement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
