# Generated by Django 4.1.2 on 2022-10-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_whoshouldenroll_jobopportunities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="description",
            name="certificate",
            field=models.ImageField(null=True, upload_to="user/"),
        ),
    ]
