# Generated by Django 3.2.6 on 2022-09-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_profile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_duration',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_overview',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
