# Generated by Django 3.2.6 on 2022-10-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20220924_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='offered_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
