# Generated by Django 4.1.2 on 2022-10-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_paytmhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paytmhistory',
            name='BANKNAME',
        ),
        migrations.RemoveField(
            model_name='paytmhistory',
            name='BANKTXNID',
        ),
        migrations.RemoveField(
            model_name='paytmhistory',
            name='GATEWAYNAME',
        ),
        migrations.RemoveField(
            model_name='paytmhistory',
            name='PAYMENTMODE',
        ),
        migrations.RemoveField(
            model_name='paytmhistory',
            name='RESPCODE',
        ),
        migrations.RemoveField(
            model_name='paytmhistory',
            name='RESPMSG',
        ),
        migrations.RemoveField(
            model_name='paytmhistory',
            name='STATUS',
        ),
        migrations.RemoveField(
            model_name='paytmhistory',
            name='TXNID',
        ),
        migrations.AlterField(
            model_name='paytmhistory',
            name='CURRENCY',
            field=models.CharField(blank=True, default='INR', max_length=4, null=True, verbose_name='CURRENCY'),
        ),
    ]
