# Generated by Django 4.1.2 on 2022-10-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_paytmhistory_bankname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paytmhistory',
            name='TXNAMOUNT',
            field=models.FloatField(default=1, verbose_name='TXN AMOUNT'),
        ),
    ]
