# Generated by Django 3.2.6 on 2022-09-14 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='AnouncementImg'),
        ),
    ]
