# Generated by Django 3.2.6 on 2022-09-14 06:37

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_announcement_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.CharField(default=courses.models.generate_slug, max_length=10),
        ),
    ]
